Feature: Test cases for deleting of existing computers

  Background:
    Given I open the Home Page
    And I click on the 'Add a new computer' button on the Home Page
    And The 'Add a computer' page should be open
    And I specify autogenerated value in the 'Computer Name' field on the 'Add a computer' page
    And I specify '2003-06-15' value in the 'Introduced date' field on the 'Add a computer' page
    And I specify '2009-08-25' value in the 'Discontinued date' field on the 'Add a computer' page
    And I specify 'IBM' value in the 'Company' field on the 'Add a computer' page
    And I click on the 'Create this computer' button
    And I preform search by the name of the created computer
    And I click on the created company in the table

  @test-10 @delete @regression
  Scenario: Deleting the existing computer
    When I click on the 'Delete' button
    Then The warning message should have the following text
    """
    Done! Computer has been deleted
    """
    And The quantity of computers should not be changed
    And I preform search by the name of the created computer
    And 'Nothing to display' message should be available

  @test-11 @delete @regression
  Scenario Outline: Deleting the existing computer, while modifying it
    When I specify '<computer_name>' value in the 'Computer name' field on the 'Add a computer' page
    And I specify '<introduced_date>' value in the 'Introduced date' field on the 'Add a computer' page
    And I specify '<discontinued_date>' value in the 'Discontinued date' field on the 'Add a computer' page
    And I specify '<company>' value in the 'Company' field on the 'Add a computer' page
    And I click on the 'Delete' button
    Then The warning message should have the following text
    """
    Done! Computer has been deleted
    """
    And The quantity of computers should not be changed
    And I preform search by the name of the created computer
    And 'Nothing to display' message should be available

    Examples:
      | computer_name | introduced_date | discontinued_date | company    |
      |               |                 |                   |            |
      |               | 1999-12-31      |                   |            |
      |               |                 | 2000-01-01        |            |
      |               |                 |                   | Apple Inc. |
      |               | 2001-11-30      | 2001-02-02        | ASUS       |
      |               | 2009-06-15      | 2010-07-03        |            |
      |               | 2011-04-28      |                   | OMRON      |
      |               |                 | 2019-02-28        | Cray       |

  @test-15 @delete @regression
  Scenario: Click on the 'Cance' button should not trigger deleting of the conputer
    When I click on the 'Cancel' button
    Then The Home Page should be open
    And I preform search by the name of the created computer
    And The table counter shows 'Displaying 1 to 1 of 1' message