Feature: Test cases for reading of existing computers

    @test-8 @read @regression
    Scenario: Checking that the created computer has the correct data
      Given I open the Home Page
      And I click on the 'Add a new computer' button on the Home Page
      And The 'Add a computer' page should be open
      And I specify autogenerated value in the 'Computer Name' field on the 'Add a computer' page
      And I specify '2003-06-15' value in the 'Introduced date' field on the 'Add a computer' page
      And I specify '2009-08-25' value in the 'Discontinued date' field on the 'Add a computer' page
      And I specify 'IBM' value in the 'Company' field on the 'Add a computer' page
      And I click on the 'Create this computer' button
      When I preform search by the name of the created computer
      Then The table counter shows 'Displaying 1 to 1 of 1' message
      And I click on the created company in the table
      And The Edit page should be open
      And 'Computer Name' field has the correct value
      And 'Introduced date' field has the correct value
      And 'Discontinued date' field has the correct value
      And 'Company' field has the correct value

    @test-12 @read @regression
    Scenario: Search computers with the same names
      Given I open the Home Page
      And I click on the 'Add a new computer' button on the Home Page
      And I specify autogenerated value in the 'Computer Name' field on the 'Add a computer' page
      And I specify '2013-10-30' value in the 'Introduced date' field on the 'Add a computer' page
      And I specify '2015-06-07' value in the 'Discontinued date' field on the 'Add a computer' page
      And I click on the 'Create this computer' button
      And I click on the 'Add a new computer' button on the Home Page
      And I specify the same value for the 'Computer Name' field as it was used before
      And I click on the 'Create this computer' button
      When I preform search by the name of the created computer
      Then The table counter shows 'Displaying 1 to 2 of 2' message

    @test-13 @read @regression
    Scenario: Search a computer by non-existing value
      Given I open the Home Page
      When I preform search by autogenerated value
      Then 'Nothing to display' message should be available

    @test-14 @read @regression
    Scenario: Search a computer by the part of its name
      Given I open the Home Page
      And I click on the 'Add a new computer' button on the Home Page
      And The 'Add a computer' page should be open
      And I specify autogenerated value in the 'Computer Name' field on the 'Add a computer' page
      And I specify '2011-10-12' value in the 'Introduced date' field on the 'Add a computer' page
      And I specify '2015-06-07' value in the 'Discontinued date' field on the 'Add a computer' page
      And I click on the 'Create this computer' button
      When I preform search by the part of the autogenerated name of the created computer
      Then The table counter shows 'Displaying 1 to 1 of 1' message
