Feature: Test cases for updating of existing computers

  Background:
    Given I open the Home Page
    And I click on the 'Add a new computer' button on the Home Page
    And The 'Add a computer' page should be open
    And I specify autogenerated value in the 'Computer Name' field on the 'Add a computer' page
    And I specify '2003-06-15' value in the 'Introduced date' field on the 'Add a computer' page
    And I specify '2009-08-25' value in the 'Discontinued date' field on the 'Add a computer' page
    And I specify 'IBM' value in the 'Company' field on the 'Add a computer' page
    And I click on the 'Create this computer' button
    And I preform search by the name of the created computer
    Then The table counter shows 'Displaying 1 to 1 of 1' message
    And I click on the created company in the table

  @test-9 @update @regression
  Scenario Outline: The updated computer has the correct data
    When I specify autogenerated value in the 'Computer Name' field on the 'Add a computer' page
    And I specify '<introduced_date>' value in the 'Introduced date' field on the 'Add a computer' page
    And I specify '<discontinued_date>' value in the 'Discontinued date' field on the 'Add a computer' page
    And I specify '<company>' value in the 'Company' field on the 'Add a computer' page
    And I click on the 'Create this computer' button
    And I preform search by the name of the created computer
    Then The table counter shows 'Displaying 1 to 1 of 1' message
    And I click on the created company in the table
    And 'Computer Name' field has the correct value
    And 'Introduced date' field has the correct value
    And 'Discontinued date' field has the correct value
    And 'Company' field has the correct value

    Examples:
      | introduced_date | discontinued_date | company             |
      | 2000-01-01      | 2000-12-31        | Sony                |
      | 2001-01-01      |                   | Apple Inc.          |
      |                 | 2002-02-01        | Samsung Electronics |
      | 1999-12-31      | 2000-01-01        |                     |
      | 1997-09-01      |                   |                     |
      |                 | 2002-02-01        |                     |
      |                 |                   | Samsung Electronics |
      |                 |                   |                     |

