package computerdatabase.steps;

import cucumber.api.java.en.Then;
import cucumber.api.java.en.When;
import org.hamcrest.MatcherAssert;

import java.util.UUID;

import static org.hamcrest.CoreMatchers.*;


public class AddComputerPageDefs extends AbstractStepDefs {

    @Then("^The 'Add a computer' page should be open$")
    public void theAddAComputerPageShouldBeOpen() {
        MatcherAssert.assertThat("The 'Add a computer' page has not been open", addComputerPage.isPageDisplayed());
    }

    @When("^I specify '([^\"]*)' value in the '(Computer name|Introduced date|Discontinued date|Company)' field on the 'Add a computer' page$")
    public void iTypeValueInTheComputerNameField(String value, String field) {
        addComputerPage.specifyField(field, value);
        if (field.equalsIgnoreCase("Computer name")) {
            if (!value.equalsIgnoreCase("")) {
                dataContainer.setDataInTestStorage(field, value);
            }
        } else {
            dataContainer.setDataInTestStorage(field, value);
        }
    }

    @When("^I specify autogenerated value in the 'Computer Name' field on the 'Add a computer' page$")
    public void iSpecifyAutogeneratedValueInTheComputerNameFieldOnTheAddAComputerPage() {
        String value = UUID.randomUUID().toString();
        addComputerPage.specifyField("Computer name", value);
        dataContainer.setDataInTestStorage("Computer name", value);
    }

    @When("^I specify the same value for the 'Computer Name' field as it was used before$")
    public void iSpecifyTheSameValueForTheComputerNameAsItWasUsedBefore() {
        addComputerPage.specifyField("Computer name", String.valueOf(dataContainer.getValueFromTestStorage("Computer name")));
    }

    @When("^I click on the 'Create this computer' button$")
    public void iClickOnTheCreateThisComputerButton() {
        addComputerPage.clickOnCreateComputerBtn();
    }

    @Then("^The warning flag should be displayed$")
    public void theWarningMessageForTheComputerNameFieldShouldBeDisplayed() {
        MatcherAssert.assertThat("The warning message for the 'Computer name' field is not displayed", addComputerPage.isValidationFlagDisplayed());
    }

    @When("^I click on the 'Cancel' button$")
    public void iClickOnTheCancelBtn() {
        addComputerPage.clickOnCancelBtn();
    }
}
